# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-name']},
        ),
    ]
