# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20161129_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['size', '-name']},
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
