# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20161129_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('BK', 'Black'), ('WH', 'White'), ('GY', 'Gray'), ('RD', 'Red'), ('BL', 'Blue'), ('GR', 'Green'), ('OR', 'Orange'), ('YW', 'Yellow'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
