# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20161129_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
