# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20161130_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(help_text='Enter description here!', max_length=500),
        ),
    ]
