# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20161130_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collat',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
