# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20161130_0326'),
        ('items', '0013_auto_20161130_0349'),
    ]

    operations = [
    ]
