# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_merge_20161130_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('BK', 'Black'), ('WH', 'White'), ('GY', 'Gray'), ('RD', 'Red'), ('BL', 'Blue'), ('GR', 'Green'), ('OR', 'Orange'), ('YW', 'Yellow'), ('OT', 'Other'), ('AL', 'ALL')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
